### ISSUE TITLE
目前init -m 貌似只能切换源

### ISSUE THREAD

**Issue by godtail** [AlloyTeam/omi-cli#1]
如果能切换安装依赖的程序好点，例如cnpm or yarn。切换了源用原生的npm安装还是感觉很慢...

**Comment by dntzhang** [comment]
可以ctrl+c 进行 cancel掉，然后用 yarn install

**Comment by pasturn** [comment]
这两天来支持这个

**Comment by godtail** [comment]
> 可以ctrl+c 进行 cancel掉，然后用 yarn install

嗯，目前我就是这样做的，当时没看源码，防止中断更新后的其他操作。

**Comment by pasturn** [comment]
#3afcdefa8b9e69a748c30c7a40957ae0523de530
