### ISSUE TITLE
建议:生成的项目能不能不要默认带上sass

### ISSUE THREAD

**Issue by seekwe** [AlloyTeam/omi-cli#3]
感觉一般情况下轻量级的less就可以搞定大部分情况 (个人建议,看到之后可以关闭该issue)

**Comment by dntzhang** [comment]
Node-sass安装慢是吗？

**Comment by dntzhang** [comment]
回头我去掉

**Comment by seekwe** [comment]
慢倒不是，主要是我很少用到py，sass需要py2，我有环境洁癖，而且sass在项目里不应该是硬性需求是吧（滑稽）

**Comment by dntzhang** [comment]
omi init-x 已移除
